
development:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  database: wave
  username: wave
  password: 5g9wg9qT3gvFacMezZcQs2W2zEHjrLJg
  encoding: unicode

test:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  database: wave
  username: wave
  password: 5g9wg9qT3gvFacMezZcQs2W2zEHjrLJg
  encoding: unicode


production:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  database: wave_production
  username: wave_production
  password: <%= ENV["WAVE_PRODUCTION_DATABASE_PASSWORD"] %>
  encoding: unicode

cable:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

queue:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

cache:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["CACHE_DATABASE_URL"] %>
