services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"
      - "18083:18083"
      - "8081:8081"
    environment:
      EMQX_LOADED_PLUGINS: "emqx_bridge_http,emqx_dashboard"
    volumes:
      - ./http_bridge.conf:/etc/emqx/plugins/emqx_bridge_http.conf
